(println "\n01. First function example")
(print "  (first \"test\") = ")
(println (first "test"))
(println "\n02. Rest function example")
(print "  (rest \"test\") = ")
(println (rest "test"))
(println "\n03. Str function example")
(print "  (str \"test\") = ")
(println (str "test"))
(println "\n04. Set function example")
(print "  (set \"test\") = ")
(println (set "test"))
(println "\n05. Subs function example")
(print "  (subs \"test\" 1) = ")
(println (subs "test" 1))
(println "\n06. Nth function example")
(print "  (nth \"test\" 1) = ")
(println (nth "test" 1))
(println "\n07. Reverse function example")
(print "  (reverse \"test\") = ")
(println (reverse "test"))
(println "\n07. Reverse function example")
(print "  (reverse \"test\") = ")
(println (reverse "test"))
(println "\n08. Drop function example")
(print "  (drop 2 \"test\") = ")
(println (drop 2 "test"))
(println "\n09. Drop-last function example")
(print "  (drop-last \"test\") = ")
(println (drop-last "test"))
(println "\n10. Count function example")
(print "  (count \"test\") = ")
(println (count "test"))
(println "\n11. Cons function example")
(print "  (cons \"test\" \"01\") = ")
(println (cons "test" "01"))
(println "\n12. Concat function example")
(print "  (concat \"test\" \"01\") = ")
(println (concat "test" "01"))
(println "\n13. Lazy-cat function example")
(print "  (lazy-cat \"test\" \"01\") = ")
(println (lazy-cat "test" "01"))
(println "\n14. Take function example")
(print "  (take 2 \"test\" = ")
(println (take 2 "test"))
(println "\n15. Take-last function example")
(print "  (take-last 2 \"test\" = ")
(println (take 2 "test"))
(println "\n16. Take-nth function example")
(print "  (take-nth 2 \"test\" = ")
(println (take-nth 2 "test"))
